### ISSUE TITLE
Dockle does not support DOCKLE_USERNAME and DOCKLE_PASSWORD

### ISSUE THREAD

**Issue by shigupt202** [goodwithtech/dockle#106]
[Azure/container-scan](https://github.com/azure/container-scan) action uses Dockle to scan images for best practice violations. However, while pulling images from Azure container registry, we get the following error.
```
Error: FATAL	unable to initialize a image struct: failed to initialize source: unable to retrieve auth token: invalid username/password: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
Error: An error occurred while scanning the container image for best practice violations
```
Is it possible to use Dockle with ACR images? From the README, it looks like it's not supported. But is there any workaround that can be suggested to the users of our action?

**Comment by tomoyamachi** [comment]
@shigupt202 As yet, Dockle does not support ACR images.
However I get start to support ACR, please wait a while longer.

**Comment by tomoyamachi** [comment]
@shigupt202 Thank you for the report. That was a bug.
Dockle did not get username and password from environment varialbes and Azure/container-scan read values from environment varialbes.
https://github.com/Azure/container-scan/blob/master/src/dockleHelper.ts#L137-L140

Dockle v3.11 is a fixed version.

**Comment by shigupt202** [comment]
Thanks @tomoyamachi for the fix! 😄
