### ISSUE TITLE
How does the dockle do with image file? 

### ISSUE THREAD

**Issue by AOxzhuweiming** [goodwithtech/dockle#108]
Hello,  I love the Dockle tool.
These are questions about Dockle, could you please take a look and answer?

Q1:
If I run the command to scan an image saved in AWS ECR, how does it do with these images?
Will Dockle download these images and saves them on local disk then scan them?
Or it just download and scan them in memory?
(Appreciate if you could point out the source code where it processes images)

Q2:
For local images, I can scan them without tag:
`dockle centos  # --> ok`
But if the images locates at remote, them tag is must to be assigned'
`dockle myrepo/centos:tag1  # --> ok`
`dockle myrepo/centos  # --> ng`

Is there any way to skip the tag for remote images also?

Thanks for your time and waiting for your reply.

**Comment by tomoyamachi** [comment]
Hi @AOxzhuweiming !

Q1. Dockle downloads file to [cache directory](https://github.com/goodwithtech/deckoder/blob/master/utils/utils.go#L12-L19) . After that dockle removes download files.

Q2.  Dockle uses `latest` tag  if users does not provide any tags.  ref : https://github.com/distribution/distribution/blob/main/reference/normalize.go#L156-L168

> Is there any way to skip the tag for remote images also?
You need to use latest tag, or you can check tags with [goodwithtech/dockertags](https://github.com/goodwithtech/dockertags) before run Dockle.

Here is a usage for newest tag before run trivy.
https://github.com/goodwithtech/dockertags#github-actions

**Comment by AOxzhuweiming** [comment]
Thank you for your answer : ）
