### ISSUE TITLE
DKL-DI-0003 should be removed

### ISSUE THREAD

**Issue by sotoiwa** [goodwithtech/dockle#110]
The best practice of avoiding `apt-get upgrade` in Dockerfile  has been removed from Docker's documentation. Dockle should also remove this check by default.

https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#dkl-di-0003

Hadolint has already removed this check. Please see the discussion in the following link.

https://github.com/docker/docker.github.io/pull/12571
https://github.com/hadolint/hadolint/issues/562

**Comment by tomoyamachi** [comment]
@sotoiwa Thank you for the report! I modified DKL-DI-0003.
Dockle v0.3.12 allows `apt-get upgrade`.
