### ISSUE TITLE
false warning: "WARN	A new version  is now available! You have v0.3.11."

### ISSUE THREAD

**Issue by peddyspg** [goodwithtech/dockle#111]
**Description**

False warning for new version is avaible 
 
>  "2021-04-20T20:00:29.138+0200	WARN	A new version  is now available! You have v0.3.11."
v03.11 is marked as latest version

**What did you expect to happen?**
No Warning.

**Output of run with `-debug`:**

```
2021-04-20T20:00:29.138+0200	WARN	A new version  is now available! You have v0.3.11.
```

**Output of `dockle -v`:**

```
dockle version 0.3.11
```

**Comment by tomoyamachi** [comment]
@peddyspg 
Thank you for the report!
I fixed it on v0.3.12 .
