### ISSUE TITLE
--no-color option

### ISSUE THREAD

**Issue by cfzlp** [goodwithtech/dockle#125]
I think it would be useful to have a command line option to disable ANSI color output.

When using dockle in build pipelines in Jenkins, sometimes it is useful to capture the output of dockle and show it somewhere, like in the Pull Request conversation. Taking the output of dockle as-is results in ANSI escape sequences being shown.

Example:

`�[33mWARN�[0m - �[36mCIS-DI-0001�[0m: Create a user for the container`

Having a --no-color option, and even supporting the [NO_COLOR](https://no-color.org/) informal standard, would be useful in these situations.

I am not an experienced Go programmer, but I volunteer to attempt a Pull Request if this suggestion is welcome.

Cheers.

**Comment by tomoyamachi** [comment]
@cfzlp Done! Please update to v0.3.17.

**Comment by cfzlp** [comment]
Awesome! Thank you.
