### ISSUE TITLE
FATAL - CIS-DI-0007 on apt-get update -y && apt-get upgrade -y

### ISSUE THREAD

**Issue by cfzlp** [goodwithtech/dockle#128]
**Description**

Dockle checkpoint CIS-DI-0007 triggers an alert on `apt-get update -y && apt-get upgrade -y`:

```
FATAL - CIS-DI-0007: Do not use update instructions alone in the Dockerfile
* Always combine 'apt-get update' with 'apt-get install' : /bin/sh -c apt-get update -y && apt-get upgrade -y
```

At the same time, dockle seems to not recognite `apt update` as equivalent as `apt-get update` and will not generate the CIS-DI-0007 when that instruction is used alone.

**What did you expect to happen?**

No alert on `apt-get update -y && apt-get upgrade -y`. Alert on `apt update`.

**What happened instead?**

Alert on `apt-get update -y && apt-get upgrade -y`. No alert on `apt update`.

**Comment by tomoyamachi** [comment]
@cfzlp 
Thank you for the report!
I fixed it on v0.3.16.
