### ISSUE TITLE
CIS-DI-0007 is not a correct option for apt-get

### ISSUE THREAD

**Issue by inductor** [goodwithtech/dockle#13]
**Description**

It says `Do not use update instructions such as apt-get update alone or in a single line in the Dockerfile.` but in fact there's no such an option for apt-get command.

```
# apt-get update --no-cache
E: Command line option --no-cache is not understood in combination with the other options
```

Maybe you're talking about apk command for Alpine?

**What did you expect to happen?**

**What happened instead?**

**Output of run with `-debug`:**

```
(paste your output here)
```

**Output of `guard -v`:**

```
(paste your output here)
```

**Additional details (base image name, container registry info...):**

**Comment by tomoyamachi** [comment]
Sorry, It's my fault.
> Do not use update instructions such as apt-get update alone or in a single line in the Dockerfile.
That means `RUN apt-get update && apt-get install -y ...`.

I will fix it soon. Thank you!

**Comment by tomoyamachi** [comment]
@inductor I fixed it.
Please update dockle!
