### ISSUE TITLE
Quiet mode just like in Trivy

### ISSUE THREAD

**Issue by nmapx** [goodwithtech/dockle#136]
I recently noticed that Dockle has similar cmd API comparing to Trivy but it lacks `quiet` mode in which it could skip printing INFO to stdout. It would resolve problems with reading JSON results directly from stdout.

**Comment by tomoyamachi** [comment]
@nmapx 
Done! Please update to v0.3.17.
By the way, you can use `dockle -o example.json -f json alpine:3.14`.
