### ISSUE TITLE
Running as root in a container should not be "FATAL"

### ISSUE THREAD

**Issue by inductor** [goodwithtech/dockle#16]
As a Docker container runs as one process on a host machine and it's separated from other processes, I do not think running as root is not "critical".

More like it won't do much even if you make it as a non-root user because it strongly depends on which user you're running Docker daemon on the host machine.

**Comment by tomoyamachi** [comment]
Currently, levels depend on CIS Benchmarks' `Profile Applicability`.

Level 1 : `FATAL`, Level 2 : `WARN`
```
Level 1 - Docker
Items in this profile intend to:
o Be practical and prudent;
o Provide a clear security benefit; and
o Not inhibit the utility of the technology beyond acceptable means.

Level 2 - Docker
Items in this profile exhibit one or more of the following characteristics:
o Are intended for environments or use cases where security is paramount o Acts as defense in depth measure
o May negatively inhibit the utility or performance of the technology
```

and `4.1 Create a user for the container` is Level 1, so I use FATAL.

But I understand your opinion.
I want to ask various people's opinions about this.

**Comment by KEINOS** [comment]
> Currently, levels depend on CIS Benchmarks' `Profile Applicability`.

Aha, the `HEALTHCHECK` thing (Issue #10 ) comes from the same reason then.

> I want to ask various people's opinions about this.

Hmm, **yes** and **no**.

Thinking of mounting `/var/run/docker.sock`, **yes**, it should be `FATAL` by default. And by omitting CIS-DI-0001 in `.dockleignore` it clarifies that the image runs as `root`.

But on the other hand,  if it's not using `/var/run/docker.sock`, which most of my containers are, then creating a user on every image breaks the simplicity of the container. So in that case **no**.

How about changing from `Create a user for the container` to `Clarify a user for the container`.

Then make it `WARN` or `PASS` if `USER root` is set in Dockerfile, and `FATAL` if nothing is set.

**Comment by KEINOS** [comment]
I checked the results of `docker inspect`.

- `USER dockle` set in Dockerfile
```shellsession
$ docker inspect my_image:my_tag | grep User | tail -1
            "User": "dockle",
```
- `USER root` set in Dockerfile
```shellsession
$ docker inspect my_image:my_tag | grep User | tail -1
            "User": "root",
```
- Nothing set in Dockerfile
```shellsession
$ docker inspect my_image:my_tag | grep User | tail -1
            "User": "",
```

**Comment by tomoyamachi** [comment]
@KEINOS @inductor  Thank you for your comment!
Now I changed meaning of level.

FATAL | Be practical and prudent
WARN | Be practical and prudent, but doesn't use in official docker image 
INFO | May negatively inhibit the utility or performance

The level of `Running as root` is WARN.

**Comment by KEINOS** [comment]
@tomoyamachi 

Wow, take a break once in a while! 😄That was quick! 👍

**Comment by 030** [comment]
Running a container as root is critical.
