### ISSUE TITLE
When a new v0.4.4 will be released?

### ISSUE THREAD

**Issue by lior-orca** [goodwithtech/dockle#166]
Is there a planned date for v0.4.4?
And if not, what does it take for Dockle to publish a new version?

Thanks.

**Comment by lior-orca** [comment]
@tomoyamachi  do you have an estimation for that?
Thanks.

**Comment by lior-orca** [comment]
@tomoyamachi can you please share an update on when a new version will be released?

**Comment by tomoyamachi** [comment]
@lior-orca v0.4.4 is now available.
