### ISSUE TITLE
containerd library update 

### ISSUE THREAD

**Issue by l00zak** [goodwithtech/dockle#173]
**Description**
I've scanned dockle using trivy, and it complains me an high severity issue in library containerd v1.5.1 used by dockle, issue seams easy to fix by updating library to at least v1.5.7 or latest v1.6.0

![image](https://user-images.githubusercontent.com/67979911/154648509-fbd96fd7-8b09-443a-84bc-098288adcdbc.png)

 

**What did you expect to happen?**

**What happened instead?**

**Output of run with `-debug`:**

```
(paste your output here)
```

**Output of `dockle -v`:**
dockle version 0.4.4
```
(paste your output here)
```

**Additional details (base image name, container registry info...):**

**Comment by tomoyamachi** [comment]
This issue has been fixed in v0.4.5.
