### ISSUE TITLE
CIS-DI-0010 reported even when environment variable is empty

### ISSUE THREAD

**Issue by SIPR-octo** [goodwithtech/dockle#180]
**Description**

The checkpoint [CIS-DI-0010](https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#cis-di-0010) is raising a `FATAL` error even when the detected environment variable is empty.

It is actually a common practice to have empty environment variable, in order to "_document_" them.

Example: `ENV POSTGRES_PASSWORD=`

**If dockle can read the environment variable value**, it would be great if it would not report in case the variable is empty.

**How to reproduce**

My `Dockerfile`:

```
FROM alpine:latest

ENV APPLE_SAUCE_SECRET=
```

The result:

```
FATAL	- CIS-DI-0010: Do not store credential in environment variables/files
	* Suspicious ENV key found : APPLE_SAUCE_SECRET (You can suppress it with --accept-key)
```

I can indeed suppress the error but I think this should not be reported as a non-compliance.

**Comment by tomoyamachi** [comment]
@SIPR-octo I've fixed it on v0.4.6.
