### ISSUE TITLE
[CIS-DI-0010] -af option should support full path ?

### ISSUE THREAD

**Issue by romainPrignon** [goodwithtech/dockle#182]
hey :)

Thanks for making dockle !

I ran into this issue this morningw hile trying to install heroku cli
Suspicious filename found : usr/local/lib/heroku/node_modules/tunnel-ssh/node_modules/ssh2-streams/test/fixtures/id_rsa
(You can suppress it with "-af id_rsa")

it work with -af id_rsa but not with the full path /usr/local/lib/heroku/node_modules/tunnel-ssh/node_modules/ssh2-streams/test/fixtures/id_rsa

What if there is another file named id_rsa that I do not want to ignore ?

**Comment by tomoyamachi** [comment]
@romainPrignon 
Currently, the `-af` parameter supports directory path or filename.

`dockle -af /usr/local/lib/heroku/node_modules/tunnel-ssh/node_modules/ssh2-streams/test/fixtures/ <param>` will be ignore `/usr/local/lib/heroku/node_modules/tunnel-ssh/node_modules/ssh2-streams/test/fixtures/id_rsa`.

I know this is not a perfect solution, but how about this approach?

**Comment by romainPrignon** [comment]
I think it will be enough for my use case.
Thank you @tomoyamachi :)
