### ISSUE TITLE
Using XDG_RUNTIME_DIR to get DOCKLE_HOST not working in GitHub runner

### ISSUE THREAD

**Issue by arman1371** [goodwithtech/dockle#188]
From today, we had a problem with our actions on in GitHub runner (ubuntu-latest). 
```
Error: FATAL	unable to initialize a image struct: failed to initialize source: reading manifest <IMAGE> in <REGISTRY>: manifest unknown: manifest tagged by <TAG> is not found
```

It seems in GitHub runner, the `XDG_RUNTIME_DIR` env value is `/run/user/1001` so dockle tries to use `unix:///run/user/1001/docker.sock` as docker sock file location and can't connect to docker.

Can we use another env as default value for checking to get `dockerSockPath`. [here](https://github.com/goodwithtech/dockle/blob/b9072c973f637e4f62b8c0bf49df705b118c4637/pkg/app.go#L37)

**Comment by iamahern** [comment]
We are seeing the same issue. Utilizing the Dockle CLI application with GitHub Actions running on an ubuntu:latest, dockle is unable to scan local images. 

Hacking this by adding:

```
env:
  XDG_RUNTIME_DIR: ""
```

To force the correct docker sock setting resolves the issue.

**Comment by tomoyamachi** [comment]
@iamahern Thanks!
