### ISSUE TITLE
False-positive detection of CIS-DI-0009 for focal based dotnet images

### ISSUE THREAD

**Issue by ThorstenHans** [goodwithtech/dockle#208]
**Description**

I ran into a situation in which dockle reports images built based on official dotnet images violating `CIS-DI-0009`.  Microsoft recently moved from Ubuntu base images hosted on Docker Hub to Canonicals images hosted on Azure Container Registry (ACR) since that move happened, `dockle` reports that all my images violate the `CIS-DI-0009` rule. 

Further information about the bug, steps to reproduce and more contextual information could be found in this issue: https://github.com/dotnet/dotnet-docker/issues/4209

**Comment by tomoyamachi** [comment]
Dockle is a tool to ensure that you are following standard best practices for container images. It does not matter if it is an official image or not.

You can use the [IGNORE](https://github.com/goodwithtech/dockle#ignore-the-specified-checkpoints) flag if you trust `ADD`ed files.
