### ISSUE TITLE
Stop alerting /tmp as suspicious directory (DKL-LI-0003)

### ISSUE THREAD

**Issue by zfLQ2qx2** [goodwithtech/dockle#215]
**Description**

Dockle 0.4.10 is reporting /tmp as a suspicious directory:

```
INFO    - DKL-LI-0003: Only put necessary files
--
400 | * unnecessary file : usr/local/share/.cache/yarn/v6/npm-@pm2-io-5.0.0-623cbcaf6fe39375f20ac2e75497477a1b1ec5c5-integrity/node_modules/@pm2/io/docker-compose.yml
401 | * Suspicious directory : tmp
```

**What did you expect to happen?**

It makes sense to remove any files in /tmp as part of the container build process, however the /tmp directory itself should always exist in a unix system, there are too many things including system functions that expect that directory to exist. Our developers had started to remove the /tmp directory to appease Dockle which caused issues when the containers tried to start.

**What happened instead?**

Dockle 0.4.10 reports /tmp as DKL-LI-0003 suspicious directory

**Comment by tomoyamachi** [comment]
Thank you for your recommendation.
I'll think about it.

**Comment by RoseSecurity** [comment]
@tomoyamachi Hey! Just opened a [PR](https://github.com/goodwithtech/dockle/pull/247) to address this ticket. Feel free to check it out if you have an opportunity.

**Comment by tomoyamachi** [comment]
@RoseSecurity Thank you for your contribution.
Your code has been included in the latest release.

**Comment by RoseSecurity** [comment]
> @RoseSecurity Thank you for your contribution.
> 
> Your code has been included in the latest release.

If you ever need help maintaining, just say the word!
