### ISSUE TITLE
Problem scanning ubuntu images

### ISSUE THREAD

**Issue by zfLQ2qx2** [goodwithtech/dockle#217]
See https://github.com/dotnet/dotnet-docker/issues/4209 for details why the CIS-DI-0009 finding is false for Ubuntu images, have confirmed same error occurs for ubuntu:latest.

**Comment by tomoyamachi** [comment]
@zfLQ2qx2 Thank you for your comment.

It is difficult to analyze whether it is a file that can be COPY or needs to be ADD from the Image.

If you get a false positive, you should use `.dockleignore` file or the `ignore` flag in that case, as you would with any other Linter.
Dockle alerts users who are not aware that ADD is dangerous.

However, I need to think a bit about whether the FATAL level is correct for this item.

**Comment by tomoyamachi** [comment]
@zfLQ2qx2  I'm sorry. I was wrong.
This issue has been fixed in version 0.4.13.
