### ISSUE TITLE
I get an invalid error about ADD/COPY

### ISSUE THREAD

**Issue by GoliTech** [goodwithtech/dockle#228]
**Description**
I get an error:
FATAL	- CIS-DI-0009: Use COPY instead of ADD in Dockerfile

	* Use COPY : /bin/sh -c #(nop) ADD file:140fb5108b4a2861b5718ad03b4a5174bba03589ea8d4c053e6a0b282f439ff3 in / 
however, I have not used either COPY or ADD in my Dockerfile.

This is my docker file:

FROM ubuntu:22.04

RUN apt-get update  

RUN apt-get install -y curl

**Comment by tomoyamachi** [comment]
@GoliTech Thank you for the report.
This issue has been fixed in version 0.4.13.
