### ISSUE TITLE
improve phrasing

### ISSUE THREAD

**Issue by tomoyamachi** [goodwithtech/dockle#25]
I'm not familiar with English.
So I wanna fix incorrect phrases at README and messages.

Please PR me😄

**Comment by KEINOS** [comment]
May I split the details to another file?

Such as the examples and CI-how-to section into `EXAMPLES.md` and
Checkpoint Detail section to `CHECKPOINT.md` file?

**Comment by tomoyamachi** [comment]
@KEINOS
OK! Thanks!

**Comment by tomoyamachi** [comment]
@KEINOS Thank you for helping me a lot!
