### ISSUE TITLE
Wrong command line argument for installation from source

### ISSUE THREAD

**Issue by porkbeans** [goodwithtech/dockle#28]
I tried to install dockle from source, but got an error below.
```
package github.com/goodwithtech/dockle: no Go files in /path/to/go/src/github.com/goodwithtech/dockle
```

In Installation from source section of `README.md`,
command shoud be `go get -u github.com/goodwithtech/dockle/cmd/dockle`?

**Comment by tomoyamachi** [comment]
@porkbeans 
I’m sorry. I didn't test it.

It seems simple `go get` doesn't recognize [`replace` statement](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive)(go module).

I worked following commands on `golang:1.12.6-stretch` container.
```
GO111MODULE=off go get github.com/goodwithtech/dockle/cmd/dockle
cd $GOPATH/src/github.com/goodwithtech/dockle && GO111MODULE=on go build -o $GOPATH/bin/dockle cmd/dockle/main.go
```

Would you try it?

Thank you for your report!

**Comment by porkbeans** [comment]
@tomoyamachi 
Thank you!
It works!
