### ISSUE TITLE
DKL-DI-0002 (Avoid sensitive directory mounting) seems too strict

### ISSUE THREAD

**Issue by AkihiroSuda** [goodwithtech/dockle#46]
https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#dkl-di-0002-avoid-sensitive-directory-mounting

> /boot, /dev, /etc, /lib, /proc, /sys, /usr

I'm not sure there can be an attack vector with these volumes, though the runtime might 
 have some vulns around mounting /dev, /proc, and /sys, potentially .

**Comment by tomoyamachi** [comment]
I misread this article. 
https://www.stackrox.com/post/2017/08/hardening-docker-containers-and-hosts-against-vulnerabilities-a-security-toolkit/#volume-mounts

You're right. I will fix it soon. Thanks.
