### ISSUE TITLE
exit code should support a level to exit on

### ISSUE THREAD

**Issue by slimm609** [goodwithtech/dockle#48]
**Description**

Exit-code should support an error level as well as exit code.

If exit-code is set to 1, it should have a level that will exit 1 on.   Currently Info will exit 1 if exit-code is set, Ideally you could set the level so if i want WARN or greater then I would set --exit-code=1 --exit-level=warn, or if i only wanted to exit on fatal, exit-level would be set to fatal.

**Comment by tomoyamachi** [comment]
@slimm609 
I did it. Please upgrade to v0.1.16.
and by default, `--exit-level warn`.
