### ISSUE TITLE
"Failed to remove image layer cache" error

### ISSUE THREAD

**Issue by shad0wrunner** [goodwithtech/dockle#50]
**Description**

On a clean virtual machine Dockle has started to throw an error with cache.
Supposedly it started after improper interruption of its execution.

**What did you expect to happen?**
After running dockle scanning process should start

**What happened instead?**
Dockle exited with "Failed to remove image layer cache" error

**Output of run with `-debug`:**

```
:~/docker_tools$ ./dockle
2019-09-03T15:49:58.672Z        FATAL   failed to remove image layer cache
osboxes@osboxes:~/docker_tools$ ./dockle --debug
2019-09-03T15:50:25.783Z        DEBUG   There is no .dockleignore file
2019-09-03T15:50:25.784Z        DEBUG   Fetch latest version from github
2019-09-03T15:50:26.744Z        FATAL   failed to remove image layer cache:
    github.com/goodwithtech/dockle/pkg.Run
        /go/src/github.com/goodwithtech/dockle/pkg/run.go:43

```

**Output of `dockle -v`:**

```
dockle version 0.1.16
```

**Additional details (base image name, container registry info...):**
Error is thrown even when running Dockle without parameters.
Is there any way to manually clear cache?

**Comment by tomoyamachi** [comment]
Thank you for the report.
Currently, you can run `dockle`(https://github.com/goodwithtech/dockle/issues/51)?

Please tell me how you did it?

**Comment by shad0wrunner** [comment]
Hi,

I have restored the clean VM image and tried again. Dockle ran fine and I wasn't able to reproduce  current issue.
The error in this report probably occured when I have abruptly stopped Dockle execution by hitting ^C - causing some cache corruption maybe?

**Comment by tomoyamachi** [comment]
Hmm... I can't reproduce it...
If something happens again, please reopen this issue.
