### ISSUE TITLE
"Failed to analyze image: failed to extract files" error

### ISSUE THREAD

**Issue by shad0wrunner** [goodwithtech/dockle#51]
**Description**

On Ubuntu VM (fresh and clean Ubuntu Server 18.10) Dockle fails to scan images.

**What did you expect to happen?**
No errors during execution

**What happened instead?**
FATAL "Failed to analyze image: failed to extract files" error 

**Output of run with `-debug`:**

```
$ ./dockle --exit-code 1 -f json --output ./dockle_results.json bkimminich/juice-shop --debug
2019-09-03T17:19:11.383Z        FATAL   failed to analyze image: failed to extract files: Could not extract the archive
osboxes@osboxes:~/docker/docker_tools$ ./dockle --debug --exit-code 1 -f json --output ./dockle_results.json bkimminich/juice-shop
2019-09-03T17:19:21.212Z        DEBUG   There is no .dockleignore file
2019-09-03T17:19:21.213Z        DEBUG   Fetch latest version from github
2019-09-03T17:19:22.282Z        DEBUG   Start assessments...
2019-09-03T17:20:22.284Z        FATAL   failed to analyze image:
    github.com/goodwithtech/dockle/pkg/scanner.ScanImage
        /go/src/github.com/goodwithtech/dockle/pkg/scanner/scan.go:32
  - failed to extract files:
    github.com/knqyf263/fanal/analyzer.Analyze
        /go/pkg/mod/github.com/goodwithtech/fanal@v0.0.0-20190706194703-57e52a04aa8b/analyzer/analyzer.go:137
  - Could not extract the archive
    github.com/knqyf263/fanal/extractor.init.ializers
        /go/pkg/mod/github.com/goodwithtech/fanal@v0.0.0-20190706194703-57e52a04aa8b/extractor/extractor.go:13
    runtime.main
        /usr/local/go/src/runtime/proc.go:188
    runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

**Output of `dockle -v`:**

```
dockle version 0.1.16
```

**Additional details (base image name, container registry info...):**
For some reason on another host dockle works fine, but on a fresh VM with Docker just installed Dockle fails.
Seems correlating to the Trivy issue - https://github.com/aquasecurity/trivy/issues/139

**Comment by masahiro331** [comment]
This problem looks like a docker timeout
The log has an error in just one minute.

**Comment by tomoyamachi** [comment]
I tried `dockle bkimminich/juice-shop` and succeed it.

Ditto @masahiro331.

You can change timeout sec `DOCKLE_TIMEOUT_SEC`.

```
DOCKLE_TIMEOUT_SEC=600s && dockle ...
   or 
docker pull <image>:<tag>
dockle <image>:<tag>
```

**Comment by shad0wrunner** [comment]
Hi, thanks for the solution. This one is solved - I've pulled the image and scanned it locally - worked like a charm.
Can I suggest more informative error message in this case? Something like "pulling image took too long. Pull it with docker pull or set DOCKLE_TIMEOUT_SEC=600s to increase the timeout"?

**Comment by tomoyamachi** [comment]
@shad0wrunner Why not? Please create the issue😄

**Comment by shad0wrunner** [comment]
No problems :) Here it is: [#52](https://github.com/goodwithtech/dockle/issues/52)
