### ISSUE TITLE
PrivilegeAssessor shouldn't exclude any directory

### ISSUE THREAD

**Issue by Silvanoc** [goodwithtech/dockle#55]
[PrivilegeAssessor](https://github.com/goodwithtech/dockle/blob/master/pkg/assessor/privilege/suid.go) is currently [ignoring any path containing `bin/` or `usr/lib/`](https://github.com/goodwithtech/dockle/blob/fe3c5496919084374d51f1f76659858bdb2b9ea2/pkg/assessor/privilege/suid.go#L14
) (excluding therefore `/bin/`, `/sbin/`, `/usr/bin/`, `/usr/lib`, but strange enough not `/usr/sbin/` or `/lib/`), but the misuse of SUID is higher to happen on executables in one of the ignored paths than someone else.

If crafting a malicious image with a SUID in it, I'd rather try to hide it under `/usr/bin` or so than placing somewhere else, where someone looking at the root-filesystem might find it strange.

I therefore wouldn't ignore any path. The corresponding checkpoint ([CIS-DI-0008](https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#cis-di-0008-remove-setuid-and-setgid-permissions-in-the-images)) can be ignored with `--ignore CIS-DI-0008`. Even if getting the issue reported, it's only `INFO` level!

The next step would be making the paths to be ignored configurable.

**Comment by tomoyamachi** [comment]
@Silvanoc 
Sorry for the late reply.
And, Thank you for the suggestion.

I will check the files containing following paths.
"bin/", "bin/", "usr/lib/", "usr/sbin/", "usr/bin/", "usr/local/bin/", "usr/local/sbin/", "usr/local/lib/"

**Comment by tomoyamachi** [comment]
@Silvanoc Sorry for the late reply, and Thank you for the suggestion.
You're right. I will show all suid and guid permissions files.

**Comment by tomoyamachi** [comment]
@Silvanoc 
I change it!
Please update v0.1.3.

**Comment by Silvanoc** [comment]
> Please update v0.1.3.

@tomoyamachi it should be v0.2.1, I'd correct that comment just in case someone else has a look at it.
