### ISSUE TITLE
using docker image in the bitbucket pipeline

### ISSUE THREAD

**Issue by thinksabin** [goodwithtech/dockle#70]
hi,
trying to use the dockle image directly in the bitbucket pipeline steps but not being able to fetch the artifact generated/ exported by the 1st step in the pipeline. the other pipeline steps with different docker images can use the .tar artifact from the 1 step but dockle image not being able to see it.
Not sure if this is dockle issue, but have you guys tried to run this in the bitbucket pipeline?

thanks

**Comment by tomoyamachi** [comment]
This issue is stale because it's been a while.
Please re-open this issue if you have still any problems.
