### ISSUE TITLE
Move `IGNORE` output to debug mode?

### ISSUE THREAD

**Issue by tokyowizard** [goodwithtech/dockle#83]
**Description**

Is it possible to remove the `IGNORE  - [checkpoint code and discription]` output in normal mode? In debug mode, it's fine.

The reason for this request is to lower the amount of unnecessary output.

**What did you expect to happen?**

No output.

**What happened instead?**

Output of the ignored checkpoint code is displayed.

```
$ dockle --exit-code=1 --ignore CIS-DI-0005 123456789012.dkr.ecr.region.amazonaws.com/my-image:0.1.0
IGNORE	- CIS-DI-0005: Enable Content trust for Docker
```

**Output of `dockle -v`:**

```
$ dockle -v
dockle version 0.3.1
```

**Comment by tomoyamachi** [comment]
@tokyowizard 
Thank you for the report!
I done it on v0.4.0.
