### ISSUE TITLE
Dockle can't detect when an image is built using buildkit mount caches

### ISSUE THREAD

**Issue by electrofelix** [goodwithtech/dockle#84]
Making use of buildkit's mount caches to cache package caches is very useful for ensuring builds on local developer machines, when the layer cache is invalidated avoid needing to download every package that was downloaded the last time the layer was built locally if the same packages are to be used.

It would be great if Dockle could detect when such caches are in place and avoid flagging failure to use `--no-cache` options for package installs because the cached files won't be present in the resulting image.

Example:
```
RUN --mount=type=cache,target=/var/cache/apk apk add --progress \
        ca-certificates \
        git \
        python3 \
        openssh \
        openssl \
        sshpass \
    ;
```
Or:
```
RUN --mount=type=cache,target=${HOME}/.cache set -xe \
    && pip3 install --upgrade pip \
    && pip3 install -r requirements.txt \
    ;
```

It's unclear whether based on scanning the image history only whether this will even be feasible, as I don't know if anything records the additional options passed to the RUN command that can be picked out. Calling `docker history --no-trunc` on the image won't show the options, so perhaps it's not available. 

In such a case it may only be possible to fully detect use of mount caches if dockle provides support to be provided the source Dockerfile to perform additional interrogation to identify this scenario.

The alternative is to inspect the file list of the corresponding layer and see if any files are present under the directory, using the absence to infer use of mount caching and downgrade the FATAL to SKIP?

**Comment by tomoyamachi** [comment]
@electrofelix It is difficult to implement that feature in the current Dockle.
Please use `.dockleignore` or `--ignore` option.

Thank you for your recommendation.
