### ISSUE TITLE
Respect $DOCKER_CONFIG env variable

### ISSUE THREAD

**Issue by jemag** [goodwithtech/dockle#87]
#### Version
dockle version: 0.3.1

#### Description

Currently if I use docker login to authenticate to a private registry, this will generate a config.json in ~/.docker/config.json. Dockle calls to the private registry will work properly after this config is created.

The problem arises when the config is not located in that exact location , that is when $DOCKER_CONFIG is different than ~/.docker

This is useful within CI/CD agents where the config.json may be be generated in a random temporary directory identified by DOCKER_CONFIG. This is also something that works with other similar tools like Trivy or Buildkit's buildctl.

**Comment by tomoyamachi** [comment]
@jemag 
Thank you for the report!
I fixed it on v0.3.17.
