### ISSUE TITLE
Option "--output" don't work on Windows

### ISSUE THREAD

**Issue by Graytotem** [goodwithtech/dockle#91]
**Description**

Option "--output" don't work on Windows (_possibly because combined with --debug_). 
After execute `dockle.exe --debug --output report.log <image_name>` the log file (_report.log_) was created, but it is empty.

**What did you expect to happen?**

I expect the application output to be redirected \ duplicated to the "report.log" file.

**What happened instead?**

Logs are output to stdout \ strerr.
The log file is created, but not filled.

**Output of run with `-debug`:**

>dockle.exe -debug --output report.log <image_name>
2021-02-15T14:51:55.550+0700    [35mDEBUG[0m  There is no .dockleignore file
2021-02-15T14:51:55.594+0700    [35mDEBUG[0m  Fetch latest version from github
2021-02-15T14:51:56.731+0700    [35mDEBUG[0m  Start assessments...
2021-02-15T14:55:25.275+0700    [35mDEBUG[0m  Start scan : password files
2021-02-15T14:55:25.275+0700    [35mDEBUG[0m  Start scan : /etc/passwd
2021-02-15T14:55:25.278+0700    [35mDEBUG[0m  Start scan : /etc/group
2021-02-15T14:55:25.287+0700    [35mDEBUG[0m  Start scan : /etc/hosts
2021-02-15T14:55:25.289+0700    [35mDEBUG[0m  Start scan : credential files
2021-02-15T14:55:25.298+0700    [35mDEBUG[0m  Scan start : config file
2021-02-15T14:55:25.301+0700    [35mDEBUG[0m  Scan start : DOCKER_CONTENT_TRUST
2021-02-15T14:55:25.303+0700    [35mDEBUG[0m  Start scan : cache files
2021-02-15T14:55:25.314+0700    [35mDEBUG[0m  End assessments...
[31mFATAL[0m  - [36mDKL-DI-0005[0m: Clear apt-get caches
        * Use 'rm -rf /var/lib/apt/lists' after 'apt-get install' : \*hidden by the author\*
[34mSKIP[0m   - [36mDKL-LI-0001[0m: Avoid empty password
        * failed to detect etc/shadow,etc/master.passwd
[34mSKIP[0m   - [36mDKL-LI-0002[0m: Be unique UID/GROUP
        * failed to detect etc/passwd
        * failed to detect etc/group
[33mWARN[0m   - [36mCIS-DI-0001[0m: Create a user for the container
        * Last user should not be root
[35mINFO[0m   - [36mCIS-DI-0005[0m: Enable Content trust for Docker
        * export DOCKER_CONTENT_TRUST=1 before docker pull/build
[35mINFO[0m   - [36mCIS-DI-0006[0m: Add HEALTHCHECK instruction to the container image
        * not found HEALTHCHECK statement
[35mINFO[0m   - [36mCIS-DI-0008[0m: Confirm safety of setuid/setgid files
        * setuid file: usr\bin\newgrp urwxr-xr-x
        * setuid file: usr\bin\mount urwxr-xr-x
        * setgid file: usr\sbin\pam_extrausers_chkpwd grwxr-xr-x
        * setuid file: usr\lib\openssh\ssh-keysign urwxr-xr-x
        * setuid file: usr\bin\su urwxr-xr-x
        * setgid file: usr\bin\ssh-agent grwxr-xr-x
        * setuid file: usr\bin\gpasswd urwxr-xr-x
        * setuid file: usr\bin\passwd urwxr-xr-x
        * setuid file: usr\bin\chsh urwxr-xr-x
        * setuid file: usr\bin\umount urwxr-xr-x
        * setuid file: usr\lib\dbus-1.0\dbus-daemon-launch-helper urwxr-xr--
        * setgid file: usr\sbin\unix_chkpwd grwxr-xr-x
        * setgid file: usr\bin\chage grwxr-xr-x
        * setgid file: usr\bin\wall grwxr-xr-x
        * setuid file: usr\bin\chfn urwxr-xr-x
        * setgid file: usr\bin\expiry grwxr-xr-x
[35mINFO[0m   - [36mDKL-LI-0003[0m: Only put necessary files
        * unnecessary file : \*hidden by the author\*

**Output of `dockle -v`:**

> dockle.exe -v
dockle version 0.3.1

**Additional details (base image name, container registry info...):**

The image and registry are private, located behind the Proxy.

**Comment by tomoyamachi** [comment]
@Graytotem Thank you for the report.
This bugs occurred on any platforms and I fixed it.
Please try on the latest version.
