### ISSUE TITLE
Add Timeout() to the Fetch Latest Version gorequest

### ISSUE THREAD

**Issue by cyberjaws** [goodwithtech/dockle#92]
The fetch latest version is taking minutes to timeout causing a slowdown in our pipeline. There is a proxy in place between the container and the destination of the fetch request.

**What did you expect to happen?**
Timeout quickly if can't reach out with warning displayed.

**What happened instead?**
Waits for 2 minutes (ish)

```
DEBUG Fetch latest version from github
```
Then a long wait...

**Comment by tomoyamachi** [comment]
Thank you for the report. I fixed it at #96.
