### ISSUE TITLE
Dockle exit code

### ISSUE THREAD

**Issue by J4CKVVH173** [goodwithtech/dockle#93]
Hello, I have a problem. I need to have exit code not equal to zero if dockle has WARN or FATAL output. I read about option -c  and I used it. But, if I use `if else` operator, if's always true but should have false. Could u explain how is it possible ?
![image](https://user-images.githubusercontent.com/33596000/108368388-6e8eef80-720b-11eb-876e-e9d239e86c78.png)

I tried different status codes but they have doing nothing.

**Comment by J4CKVVH173** [comment]
I find a solution for bash.
First step I execute dockle `./dockle -f json --exit-code 1` and then I use `&?` bash operator.  ` if [ \$? -eq 1  ]; then exit 1; fi`
It works for me

**Comment by tomoyamachi** [comment]
`if [[ $(command) ]]` statement just checks no character on stdout.
`Dockle` output result to stdout without an `output` argument.
